  0%|                                                                                         | 0/5000 [00:00<?, ?it/s]C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
Saving model in ../model/ppo
model saved















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































 23%|████████████████▊                                                         | 1135/5000 [1:52:52<6:24:23,  5.97s/it]
Traceback (most recent call last):
  File "D:\Projects\Python\ReinforcementLearning\project_2_a2c\pongGame_A2C\main.py", line 45, in <module>
    main()
  File "D:\Projects\Python\ReinforcementLearning\project_2_a2c\pongGame_A2C\main.py", line 24, in main
    rewards_history = agent.train(pw)
  File "D:\Projects\Python\ReinforcementLearning\project_2_a2c\pongGame_A2C\agent.py", line 92, in train
    grads = tape.gradient(loss, self.model.trainable_variables)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\eager\backprop.py", line 1065, in gradient
    flat_grad = imperative_grad.imperative_grad(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\eager\imperative_grad.py", line 67, in imperative_grad
    return pywrap_tfe.TFE_Py_TapeGradient(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\eager\backprop.py", line 147, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\ops\nn_grad.py", line 583, in _Conv2DGrad
    gen_nn_ops.conv2d_backprop_input(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 2025, in conv2d_backprop_input
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Projects\Python\ReinforcementLearning\project_2_a2c\pongGame_A2C\main.py", line 52, in <module>
    agent.save_model(model_path)
  File "D:\Projects\Python\ReinforcementLearning\project_2_a2c\pongGame_A2C\agent.py", line 219, in save_model
    return -tf.reduce_mean(surrogate) - self.entropy_c * kloss.categorical_crossentropy(new_policy, new_policy)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\engine\training.py", line 3079, in save
    saving_api.save_model(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\saving\saving_api.py", line 167, in save_model
    return legacy_sm_saving_lib.save_model(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\saving\legacy\save.py", line 168, in save_model
    saved_model_save.save(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\saving\legacy\saved_model\save.py", line 98, in save
    saved_nodes, node_paths = save_lib.save_and_return_nodes(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\saved_model\save.py", line 1366, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\saved_model\save.py", line 1578, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\saved_model\save.py", line 1502, in _build_meta_graph_impl
    saveable_view = _SaveableView(augmented_graph_view, options)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\saved_model\save.py", line 284, in __init__
    checkpoint_util.objects_ids_and_slot_variables_and_paths(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\util.py", line 157, in objects_ids_and_slot_variables_and_paths
    trackable_objects, node_paths = graph_view.breadth_first_traversal()
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 124, in breadth_first_traversal
    return self._breadth_first_traversal()
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\saved_model\save.py", line 155, in _breadth_first_traversal
    super(_AugmentedGraphView, self)._breadth_first_traversal())
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 128, in _breadth_first_traversal
    return super(ObjectGraphView, self)._descendants_with_paths()
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\trackable_view.py", line 111, in _descendants_with_paths
    for name, dependency in self.children(current_trackable).items():
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 97, in children
    for name, ref in self.list_children(obj, **kwargs):
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\saved_model\save.py", line 189, in list_children
    for name, child in super(_AugmentedGraphView, self).list_children(
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\graph_view.py", line 75, in list_children
    for name, ref in super(ObjectGraphView,
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\checkpoint\trackable_view.py", line 84, in children
    for name, ref in obj._trackable_children(save_type, **kwargs).items():
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\engine\training.py", line 4002, in _trackable_children
    children = super()._trackable_children(save_type, **kwargs)
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\keras\src\engine\base_layer.py", line 3475, in _trackable_children
    children.update(super()._trackable_children(save_type, **kwargs))
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\site-packages\tensorflow\python\trackable\autotrackable.py", line 93, in _trackable_children
    with warnings.catch_warnings():
  File "C:\Users\HEEKWON\anaconda3\envs\rl_a2c\lib\warnings.py", line 458, in __enter__
    def __enter__(self):
KeyboardInterrupt